modLoader="javafml" #mandatory

loaderVersion="[37,)" #mandatory (36 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional
license="MIT"

[[mods]] #mandatory
modId="easy_emerald" #mandatory
version="1.2.7" #mandatory
displayName="Easy Emerald" #mandatory
description='''
Gear made from gems
'''


[[dependencies.easy_emerald]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37.0.31,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.easy_emerald]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"
